var dir_832dc65d35285dfcb7b4cab200ffec62 =
[
    [ "AbandonMarketPlugin.java", "d2/d7a/AbandonMarketPlugin_8java.html", "d2/d7a/AbandonMarketPlugin_8java" ],
    [ "CommodityFlowAPI.java", "da/d28/CommodityFlowAPI_8java.html", "da/d28/CommodityFlowAPI_8java" ],
    [ "CommodityMarketDataAPI.java", "d6/d7b/CommodityMarketDataAPI_8java.html", "d6/d7b/CommodityMarketDataAPI_8java" ],
    [ "CommodityOnMarketAPI.java", "d3/d8a/CommodityOnMarketAPI_8java.html", "d3/d8a/CommodityOnMarketAPI_8java" ],
    [ "CommoditySourceType.java", "da/df6/CommoditySourceType_8java.html", "da/df6/CommoditySourceType_8java" ],
    [ "CommoditySpecAPI.java", "df/da1/CommoditySpecAPI_8java.html", "df/da1/CommoditySpecAPI_8java" ],
    [ "EconomyAPI.java", "d4/dad/EconomyAPI_8java.html", "d4/dad/EconomyAPI_8java" ],
    [ "ImmigrationPlugin.java", "d0/d9c/ImmigrationPlugin_8java.html", "d0/d9c/ImmigrationPlugin_8java" ],
    [ "Industry.java", "d1/d89/Industry_8java.html", "d1/d89/Industry_8java" ],
    [ "InstallableIndustryItemPlugin.java", "d6/d5f/InstallableIndustryItemPlugin_8java.html", "d6/d5f/InstallableIndustryItemPlugin_8java" ],
    [ "MarketAPI.java", "dc/d26/MarketAPI_8java.html", "dc/d26/MarketAPI_8java" ],
    [ "MarketConditionAPI.java", "d4/dd8/MarketConditionAPI_8java.html", "d4/dd8/MarketConditionAPI_8java" ],
    [ "MarketConditionPlugin.java", "dc/d7d/MarketConditionPlugin_8java.html", "dc/d7d/MarketConditionPlugin_8java" ],
    [ "MarketConnectionAPI.java", "d0/d7b/MarketConnectionAPI_8java.html", "d0/d7b/MarketConnectionAPI_8java" ],
    [ "MarketDemandAPI.java", "d0/dc8/MarketDemandAPI_8java.html", "d0/dc8/MarketDemandAPI_8java" ],
    [ "MarketDemandDataAPI.java", "d3/dee/MarketDemandDataAPI_8java.html", "d3/dee/MarketDemandDataAPI_8java" ],
    [ "MarketImmigrationModifier.java", "df/d71/MarketImmigrationModifier_8java.html", "df/d71/MarketImmigrationModifier_8java" ],
    [ "MarketShareDataAPI.java", "da/d43/MarketShareDataAPI_8java.html", "da/d43/MarketShareDataAPI_8java" ],
    [ "MonthlyReport.java", "df/d4c/MonthlyReport_8java.html", "df/d4c/MonthlyReport_8java" ],
    [ "MutableCommodityQuantity.java", "da/da2/MutableCommodityQuantity_8java.html", "da/da2/MutableCommodityQuantity_8java" ],
    [ "PriceVariability.java", "dd/d2f/PriceVariability_8java.html", "dd/d2f/PriceVariability_8java" ],
    [ "StabilizeMarketPlugin.java", "dd/dc0/StabilizeMarketPlugin_8java.html", "dd/dc0/StabilizeMarketPlugin_8java" ],
    [ "SubmarketAPI.java", "d5/dee/SubmarketAPI_8java.html", "d5/dee/SubmarketAPI_8java" ],
    [ "SubmarketSpecAPI.java", "dd/dfa/SubmarketSpecAPI_8java.html", "dd/dfa/SubmarketSpecAPI_8java" ],
    [ "TransactionDataAPI.java", "da/d6c/TransactionDataAPI_8java.html", "da/d6c/TransactionDataAPI_8java" ],
    [ "TransferTotalAPI.java", "d3/db5/TransferTotalAPI_8java.html", "d3/db5/TransferTotalAPI_8java" ]
];