var dir_dcebe147640cd34a611211efc2ffc8d2 =
[
    [ "AsteroidBeltTerrainPlugin.java", "AsteroidBeltTerrainPlugin_8java.html", "AsteroidBeltTerrainPlugin_8java" ],
    [ "AsteroidFieldTerrainPlugin.java", "AsteroidFieldTerrainPlugin_8java.html", "AsteroidFieldTerrainPlugin_8java" ],
    [ "AsteroidImpact.java", "AsteroidImpact_8java.html", "AsteroidImpact_8java" ],
    [ "AsteroidSource.java", "AsteroidSource_8java.html", "AsteroidSource_8java" ],
    [ "AuroraRenderer.java", "AuroraRenderer_8java.html", "AuroraRenderer_8java" ],
    [ "BaseRingTerrain.java", "BaseRingTerrain_8java.html", "BaseRingTerrain_8java" ],
    [ "BaseTerrain.java", "BaseTerrain_8java.html", "BaseTerrain_8java" ],
    [ "BaseTiledTerrain.java", "BaseTiledTerrain_8java.html", "BaseTiledTerrain_8java" ],
    [ "CRLossPerSecondBuff.java", "CRLossPerSecondBuff_8java.html", "CRLossPerSecondBuff_8java" ],
    [ "CRRecoveryBuff.java", "CRRecoveryBuff_8java.html", "CRRecoveryBuff_8java" ],
    [ "DebrisFieldTerrainPlugin.java", "DebrisFieldTerrainPlugin_8java.html", "DebrisFieldTerrainPlugin_8java" ],
    [ "DebrisPiece.java", "DebrisPiece_8java.html", "DebrisPiece_8java" ],
    [ "EventHorizonPlugin.java", "EventHorizonPlugin_8java.html", "EventHorizonPlugin_8java" ],
    [ "FlareManager.java", "FlareManager_8java.html", "FlareManager_8java" ],
    [ "HyperspaceAutomaton.java", "HyperspaceAutomaton_8java.html", "HyperspaceAutomaton_8java" ],
    [ "HyperspaceTerrainPlugin.java", "HyperspaceTerrainPlugin_8java.html", "HyperspaceTerrainPlugin_8java" ],
    [ "HyperStormBoost.java", "HyperStormBoost_8java.html", "HyperStormBoost_8java" ],
    [ "MagneticFieldTerrainPlugin.java", "MagneticFieldTerrainPlugin_8java.html", "MagneticFieldTerrainPlugin_8java" ],
    [ "MaxBurnBuff.java", "MaxBurnBuff_8java.html", "MaxBurnBuff_8java" ],
    [ "NebulaTerrainPlugin.java", "NebulaTerrainPlugin_8java.html", "NebulaTerrainPlugin_8java" ],
    [ "PeakPerformanceBuff.java", "PeakPerformanceBuff_8java.html", "PeakPerformanceBuff_8java" ],
    [ "PulsarBeamTerrainPlugin.java", "PulsarBeamTerrainPlugin_8java.html", "PulsarBeamTerrainPlugin_8java" ],
    [ "PulsarRenderer.java", "PulsarRenderer_8java.html", "PulsarRenderer_8java" ],
    [ "RadioChatterTerrainPlugin.java", "RadioChatterTerrainPlugin_8java.html", "RadioChatterTerrainPlugin_8java" ],
    [ "RangeBlockerUtil.java", "RangeBlockerUtil_8java.html", "RangeBlockerUtil_8java" ],
    [ "RingRenderer.java", "RingRenderer_8java.html", "RingRenderer_8java" ],
    [ "RingSystemTerrainPlugin.java", "RingSystemTerrainPlugin_8java.html", "RingSystemTerrainPlugin_8java" ],
    [ "ShoveFleetScript.java", "ShoveFleetScript_8java.html", "ShoveFleetScript_8java" ],
    [ "SlipstreamTerrainPlugin.java", "SlipstreamTerrainPlugin_8java.html", "SlipstreamTerrainPlugin_8java" ],
    [ "SpatialAnomalyTerrainPlugin.java", "SpatialAnomalyTerrainPlugin_8java.html", "SpatialAnomalyTerrainPlugin_8java" ],
    [ "StarCoronaAkaMainyuTerrainPlugin.java", "StarCoronaAkaMainyuTerrainPlugin_8java.html", "StarCoronaAkaMainyuTerrainPlugin_8java" ],
    [ "StarCoronaJetTerrainPlugin.java", "StarCoronaJetTerrainPlugin_8java.html", "StarCoronaJetTerrainPlugin_8java" ],
    [ "StarCoronaTerrainPlugin.java", "StarCoronaTerrainPlugin_8java.html", "StarCoronaTerrainPlugin_8java" ],
    [ "WavefrontTerrainPlugin.java", "WavefrontTerrainPlugin_8java.html", "WavefrontTerrainPlugin_8java" ]
];