var dir_853a2ff8fdf1442eab695dd19ea9b8f6 =
[
    [ "AbilityPlugin.java", "d0/d57/AbilityPlugin_8java.html", "d0/d57/AbilityPlugin_8java" ],
    [ "AdminData.java", "d4/d62/AdminData_8java.html", "d4/d62/AdminData_8java" ],
    [ "AfterShipCreationSkillEffect.java", "d4/d19/AfterShipCreationSkillEffect_8java.html", "d4/d19/AfterShipCreationSkillEffect_8java" ],
    [ "BaseSkillsChangeEffect.java", "d9/dd0/BaseSkillsChangeEffect_8java.html", "d9/dd0/BaseSkillsChangeEffect_8java" ],
    [ "CharacterCreationData.java", "d3/d70/CharacterCreationData_8java.html", "d3/d70/CharacterCreationData_8java" ],
    [ "CharacterStatsSkillEffect.java", "dd/de1/CharacterStatsSkillEffect_8java.html", "dd/de1/CharacterStatsSkillEffect_8java" ],
    [ "CustomSkillDescription.java", "d2/dab/CustomSkillDescription_8java.html", "d2/dab/CustomSkillDescription_8java" ],
    [ "DescriptionSkillEffect.java", "d8/dfb/DescriptionSkillEffect_8java.html", "d8/dfb/DescriptionSkillEffect_8java" ],
    [ "FleetStatsSkillEffect.java", "d1/d7b/FleetStatsSkillEffect_8java.html", "d1/d7b/FleetStatsSkillEffect_8java" ],
    [ "FleetTotalItem.java", "d4/d0f/FleetTotalItem_8java.html", "d4/d0f/FleetTotalItem_8java" ],
    [ "FleetTotalSource.java", "d0/dbb/FleetTotalSource_8java.html", "d0/dbb/FleetTotalSource_8java" ],
    [ "FullName.java", "d9/d3a/FullName_8java.html", "d9/d3a/FullName_8java" ],
    [ "ImportantPeopleAPI.java", "d9/dce/ImportantPeopleAPI_8java.html", "d9/dce/ImportantPeopleAPI_8java" ],
    [ "LevelBasedEffect.java", "d1/ddf/LevelBasedEffect_8java.html", "d1/ddf/LevelBasedEffect_8java" ],
    [ "MarketConditionSpecAPI.java", "d7/da1/MarketConditionSpecAPI_8java.html", "d7/da1/MarketConditionSpecAPI_8java" ],
    [ "MarketPostPersonFilter.java", "d7/d61/MarketPostPersonFilter_8java.html", "d7/d61/MarketPostPersonFilter_8java" ],
    [ "MarketSkillEffect.java", "dd/d88/MarketSkillEffect_8java.html", "dd/d88/MarketSkillEffect_8java" ],
    [ "MutableCharacterStatsAPI.java", "dd/d27/MutableCharacterStatsAPI_8java.html", "dd/d27/MutableCharacterStatsAPI_8java" ],
    [ "OfficerDataAPI.java", "d1/df4/OfficerDataAPI_8java.html", "d1/df4/OfficerDataAPI_8java" ],
    [ "PersonalityAPI.java", "dd/d3c/PersonalityAPI_8java.html", "dd/d3c/PersonalityAPI_8java" ],
    [ "PersonAPI.java", "d0/da8/PersonAPI_8java.html", "d0/da8/PersonAPI_8java" ],
    [ "RelationshipAPI.java", "d1/d00/RelationshipAPI_8java.html", "d1/d00/RelationshipAPI_8java" ],
    [ "ShipSkillEffect.java", "d9/d8d/ShipSkillEffect_8java.html", "d9/d8d/ShipSkillEffect_8java" ],
    [ "SkillEffectType.java", "d0/d34/SkillEffectType_8java.html", "d0/d34/SkillEffectType_8java" ],
    [ "SkillsChangeEffect.java", "dc/d86/SkillsChangeEffect_8java.html", "dc/d86/SkillsChangeEffect_8java" ],
    [ "SkillsChangeOfficerEffect.java", "dd/dd4/SkillsChangeOfficerEffect_8java.html", "dd/dd4/SkillsChangeOfficerEffect_8java" ],
    [ "SkillsChangeRemoveExcessOPEffect.java", "d3/d8c/SkillsChangeRemoveExcessOPEffect_8java.html", "d3/d8c/SkillsChangeRemoveExcessOPEffect_8java" ],
    [ "SkillsChangeRemoveSmodsEffect.java", "d1/d8e/SkillsChangeRemoveSmodsEffect_8java.html", "d1/d8e/SkillsChangeRemoveSmodsEffect_8java" ],
    [ "SkillsChangeRemoveVentsCapsEffect.java", "d7/d93/SkillsChangeRemoveVentsCapsEffect_8java.html", "d7/d93/SkillsChangeRemoveVentsCapsEffect_8java" ],
    [ "SkillSpecAPI.java", "d3/d77/SkillSpecAPI_8java.html", "d3/d77/SkillSpecAPI_8java" ]
];