var dir_34de85de80cdc252256f5aeed6fe2690 =
[
    [ "Abilities.java", "dc/d7f/Abilities_8java.html", "dc/d7f/Abilities_8java" ],
    [ "BattleObjectives.java", "d4/d4a/BattleObjectives_8java.html", "d4/d4a/BattleObjectives_8java" ],
    [ "Commodities.java", "dc/d43/Commodities_8java.html", "dc/d43/Commodities_8java" ],
    [ "Conditions.java", "d5/d79/Conditions_8java.html", "d5/d79/Conditions_8java" ],
    [ "Difficulties.java", "d8/d06/Difficulties_8java.html", "d8/d06/Difficulties_8java" ],
    [ "Drops.java", "d4/dc0/Drops_8java.html", "d4/dc0/Drops_8java" ],
    [ "Entities.java", "d8/d41/Entities_8java.html", "d8/d41/Entities_8java" ],
    [ "Events.java", "d9/d45/Events_8java.html", "d9/d45/Events_8java" ],
    [ "Factions.java", "d9/d74/Factions_8java.html", "d9/d74/Factions_8java" ],
    [ "FleetTypes.java", "d6/dbe/FleetTypes_8java.html", "d6/dbe/FleetTypes_8java" ],
    [ "HullMods.java", "dc/dc2/HullMods_8java.html", "dc/dc2/HullMods_8java" ],
    [ "Industries.java", "d7/deb/Industries_8java.html", "d7/deb/Industries_8java" ],
    [ "Items.java", "d1/d0f/Items_8java.html", "d1/d0f/Items_8java" ],
    [ "MemFlags.java", "d0/da0/MemFlags_8java.html", "d0/da0/MemFlags_8java" ],
    [ "Missions.java", "dd/dff/Missions_8java.html", "dd/dff/Missions_8java" ],
    [ "People.java", "db/d00/People_8java.html", "db/d00/People_8java" ],
    [ "Personalities.java", "de/d14/Personalities_8java.html", "de/d14/Personalities_8java" ],
    [ "Pings.java", "d7/da3/Pings_8java.html", "d7/da3/Pings_8java" ],
    [ "Planets.java", "db/d28/Planets_8java.html", "db/d28/Planets_8java" ],
    [ "Ranks.java", "d2/d59/Ranks_8java.html", "d2/d59/Ranks_8java" ],
    [ "ShipRoles.java", "da/d51/ShipRoles_8java.html", "da/d51/ShipRoles_8java" ],
    [ "Skills.java", "d4/d8d/Skills_8java.html", "d4/d8d/Skills_8java" ],
    [ "Sounds.java", "df/dd3/Sounds_8java.html", "df/dd3/Sounds_8java" ],
    [ "StarTypes.java", "d5/d3f/StarTypes_8java.html", "d5/d3f/StarTypes_8java" ],
    [ "Stats.java", "d6/deb/Stats_8java.html", "d6/deb/Stats_8java" ],
    [ "Strings.java", "da/d5a/Strings_8java.html", "da/d5a/Strings_8java" ],
    [ "Submarkets.java", "d0/dd4/Submarkets_8java.html", "d0/dd4/Submarkets_8java" ],
    [ "Tags.java", "df/d69/Tags_8java.html", "df/d69/Tags_8java" ],
    [ "Terrain.java", "d2/d15/Terrain_8java.html", "d2/d15/Terrain_8java" ],
    [ "Voices.java", "d8/dfd/Voices_8java.html", "d8/dfd/Voices_8java" ]
];