var dir_d48b5f679b0918c9a50e976f6a24181c =
[
    [ "AbilitySpecAPI.java", "AbilitySpecAPI_8java.html", "AbilitySpecAPI_8java" ],
    [ "BarEventSpec.java", "BarEventSpec_8java.html", "BarEventSpec_8java" ],
    [ "CampaignPingSpec.java", "CampaignPingSpec_8java.html", "CampaignPingSpec_8java" ],
    [ "ContactTagSpec.java", "ContactTagSpec_8java.html", "ContactTagSpec_8java" ],
    [ "DamagingExplosionSpec.java", "DamagingExplosionSpec_8java.html", "DamagingExplosionSpec_8java" ],
    [ "Description.java", "Description_8java.html", "Description_8java" ],
    [ "EventSpecAPI.java", "EventSpecAPI_8java.html", "EventSpecAPI_8java" ],
    [ "FighterWingSpecAPI.java", "FighterWingSpecAPI_8java.html", "FighterWingSpecAPI_8java" ],
    [ "FormationType.java", "FormationType_8java.html", "FormationType_8java" ],
    [ "HullModSpecAPI.java", "HullModSpecAPI_8java.html", "HullModSpecAPI_8java" ],
    [ "IndustrySpecAPI.java", "IndustrySpecAPI_8java.html", "IndustrySpecAPI_8java" ],
    [ "MissileSpecAPI.java", "MissileSpecAPI_8java.html", "MissileSpecAPI_8java" ],
    [ "MuzzleFlashSpec.java", "MuzzleFlashSpec_8java.html", "MuzzleFlashSpec_8java" ],
    [ "PersonMissionSpec.java", "PersonMissionSpec_8java.html", "PersonMissionSpec_8java" ],
    [ "ProjectileSpawnType.java", "ProjectileSpawnType_8java.html", "ProjectileSpawnType_8java" ],
    [ "ProjectileSpecAPI.java", "ProjectileSpecAPI_8java.html", "ProjectileSpecAPI_8java" ],
    [ "ProjectileWeaponSpecAPI.java", "ProjectileWeaponSpecAPI_8java.html", "ProjectileWeaponSpecAPI_8java" ],
    [ "RoleEntryAPI.java", "RoleEntryAPI_8java.html", "RoleEntryAPI_8java" ],
    [ "ShotBehaviorSpecAPI.java", "ShotBehaviorSpecAPI_8java.html", "ShotBehaviorSpecAPI_8java" ],
    [ "TerrainSpecAPI.java", "TerrainSpecAPI_8java.html", "TerrainSpecAPI_8java" ],
    [ "VariantSource.java", "VariantSource_8java.html", "VariantSource_8java" ],
    [ "WeaponGroupSpec.java", "WeaponGroupSpec_8java.html", "WeaponGroupSpec_8java" ],
    [ "WeaponGroupType.java", "WeaponGroupType_8java.html", "WeaponGroupType_8java" ],
    [ "WeaponSlotAPI.java", "WeaponSlotAPI_8java.html", "WeaponSlotAPI_8java" ],
    [ "WeaponSpecAPI.java", "WeaponSpecAPI_8java.html", "WeaponSpecAPI_8java" ],
    [ "WingRole.java", "WingRole_8java.html", "WingRole_8java" ]
];