var dir_d48b5f679b0918c9a50e976f6a24181c =
[
    [ "AbilitySpecAPI.java", "db/d07/AbilitySpecAPI_8java.html", "db/d07/AbilitySpecAPI_8java" ],
    [ "BarEventSpec.java", "d2/de8/BarEventSpec_8java.html", "d2/de8/BarEventSpec_8java" ],
    [ "CampaignPingSpec.java", "d9/daf/CampaignPingSpec_8java.html", "d9/daf/CampaignPingSpec_8java" ],
    [ "ContactTagSpec.java", "d2/ddb/ContactTagSpec_8java.html", "d2/ddb/ContactTagSpec_8java" ],
    [ "DamagingExplosionSpec.java", "d8/d7a/DamagingExplosionSpec_8java.html", "d8/d7a/DamagingExplosionSpec_8java" ],
    [ "Description.java", "d4/dbd/Description_8java.html", "d4/dbd/Description_8java" ],
    [ "EventSpecAPI.java", "d4/d41/EventSpecAPI_8java.html", "d4/d41/EventSpecAPI_8java" ],
    [ "FighterWingSpecAPI.java", "d2/d49/FighterWingSpecAPI_8java.html", "d2/d49/FighterWingSpecAPI_8java" ],
    [ "FormationType.java", "dd/dcd/FormationType_8java.html", "dd/dcd/FormationType_8java" ],
    [ "HullModSpecAPI.java", "d0/dc3/HullModSpecAPI_8java.html", "d0/dc3/HullModSpecAPI_8java" ],
    [ "IndustrySpecAPI.java", "d6/d20/IndustrySpecAPI_8java.html", "d6/d20/IndustrySpecAPI_8java" ],
    [ "MissileSpecAPI.java", "d2/db5/MissileSpecAPI_8java.html", "d2/db5/MissileSpecAPI_8java" ],
    [ "MuzzleFlashSpec.java", "df/daa/MuzzleFlashSpec_8java.html", "df/daa/MuzzleFlashSpec_8java" ],
    [ "PersonMissionSpec.java", "d3/d56/PersonMissionSpec_8java.html", "d3/d56/PersonMissionSpec_8java" ],
    [ "ProjectileSpawnType.java", "db/dcc/ProjectileSpawnType_8java.html", "db/dcc/ProjectileSpawnType_8java" ],
    [ "ProjectileSpecAPI.java", "d1/d85/ProjectileSpecAPI_8java.html", "d1/d85/ProjectileSpecAPI_8java" ],
    [ "ProjectileWeaponSpecAPI.java", "d2/dea/ProjectileWeaponSpecAPI_8java.html", "d2/dea/ProjectileWeaponSpecAPI_8java" ],
    [ "RoleEntryAPI.java", "d4/d60/RoleEntryAPI_8java.html", "d4/d60/RoleEntryAPI_8java" ],
    [ "ShotBehaviorSpecAPI.java", "dd/d26/ShotBehaviorSpecAPI_8java.html", "dd/d26/ShotBehaviorSpecAPI_8java" ],
    [ "TerrainSpecAPI.java", "d2/d1b/TerrainSpecAPI_8java.html", "d2/d1b/TerrainSpecAPI_8java" ],
    [ "VariantSource.java", "d3/d85/VariantSource_8java.html", "d3/d85/VariantSource_8java" ],
    [ "WeaponGroupSpec.java", "dd/d7e/WeaponGroupSpec_8java.html", "dd/d7e/WeaponGroupSpec_8java" ],
    [ "WeaponGroupType.java", "d1/dbd/WeaponGroupType_8java.html", "d1/dbd/WeaponGroupType_8java" ],
    [ "WeaponSlotAPI.java", "d4/dbd/WeaponSlotAPI_8java.html", "d4/dbd/WeaponSlotAPI_8java" ],
    [ "WeaponSpecAPI.java", "de/ddc/WeaponSpecAPI_8java.html", "de/ddc/WeaponSpecAPI_8java" ],
    [ "WingRole.java", "dd/d58/WingRole_8java.html", "dd/d58/WingRole_8java" ]
];