var dir_34de85de80cdc252256f5aeed6fe2690 =
[
    [ "Abilities.java", "Abilities_8java.html", "Abilities_8java" ],
    [ "BattleObjectives.java", "BattleObjectives_8java.html", "BattleObjectives_8java" ],
    [ "Commodities.java", "Commodities_8java.html", "Commodities_8java" ],
    [ "Conditions.java", "Conditions_8java.html", "Conditions_8java" ],
    [ "Difficulties.java", "Difficulties_8java.html", "Difficulties_8java" ],
    [ "Drops.java", "Drops_8java.html", "Drops_8java" ],
    [ "Entities.java", "Entities_8java.html", "Entities_8java" ],
    [ "Events.java", "Events_8java.html", "Events_8java" ],
    [ "Factions.java", "Factions_8java.html", "Factions_8java" ],
    [ "FleetTypes.java", "FleetTypes_8java.html", "FleetTypes_8java" ],
    [ "HullMods.java", "HullMods_8java.html", "HullMods_8java" ],
    [ "Industries.java", "Industries_8java.html", "Industries_8java" ],
    [ "Items.java", "Items_8java.html", "Items_8java" ],
    [ "MemFlags.java", "MemFlags_8java.html", "MemFlags_8java" ],
    [ "Missions.java", "Missions_8java.html", "Missions_8java" ],
    [ "People.java", "People_8java.html", "People_8java" ],
    [ "Personalities.java", "Personalities_8java.html", "Personalities_8java" ],
    [ "Pings.java", "Pings_8java.html", "Pings_8java" ],
    [ "Planets.java", "Planets_8java.html", "Planets_8java" ],
    [ "Ranks.java", "Ranks_8java.html", "Ranks_8java" ],
    [ "ShipRoles.java", "ShipRoles_8java.html", "ShipRoles_8java" ],
    [ "Skills.java", "Skills_8java.html", "Skills_8java" ],
    [ "Sounds.java", "Sounds_8java.html", "Sounds_8java" ],
    [ "StarTypes.java", "StarTypes_8java.html", "StarTypes_8java" ],
    [ "Stats.java", "Stats_8java.html", "Stats_8java" ],
    [ "Strings.java", "Strings_8java.html", "Strings_8java" ],
    [ "Submarkets.java", "Submarkets_8java.html", "Submarkets_8java" ],
    [ "Tags.java", "Tags_8java.html", "Tags_8java" ],
    [ "Terrain.java", "Terrain_8java.html", "Terrain_8java" ],
    [ "Voices.java", "Voices_8java.html", "Voices_8java" ]
];