var dir_d5434224a326a4bb5c940eae5d8b61ff =
[
    [ "ai", "dir_0426b9c052d5b89a4a623b93dcad6309.html", "dir_0426b9c052d5b89a4a623b93dcad6309" ],
    [ "BaseAbilityPlugin.java", "BaseAbilityPlugin_8java.html", "BaseAbilityPlugin_8java" ],
    [ "BaseDurationAbility.java", "BaseDurationAbility_8java.html", "BaseDurationAbility_8java" ],
    [ "BaseToggleAbility.java", "BaseToggleAbility_8java.html", "BaseToggleAbility_8java" ],
    [ "DistressCallAbility.java", "DistressCallAbility_8java.html", "DistressCallAbility_8java" ],
    [ "DistressCallResponseAssignmentAI.java", "DistressCallResponseAssignmentAI_8java.html", "DistressCallResponseAssignmentAI_8java" ],
    [ "DistressCallResponsePirateAssignmentAI.java", "DistressCallResponsePirateAssignmentAI_8java.html", "DistressCallResponsePirateAssignmentAI_8java" ],
    [ "DurationAbilityWithCost2.java", "DurationAbilityWithCost2_8java.html", "DurationAbilityWithCost2_8java" ],
    [ "EmergencyBurnAbility.java", "EmergencyBurnAbility_8java.html", "EmergencyBurnAbility_8java" ],
    [ "FractureJumpAbility.java", "FractureJumpAbility_8java.html", "FractureJumpAbility_8java" ],
    [ "GenerateSlipsurgeAbility.java", "GenerateSlipsurgeAbility_8java.html", "GenerateSlipsurgeAbility_8java" ],
    [ "GoDarkAbility.java", "GoDarkAbility_8java.html", "GoDarkAbility_8java" ],
    [ "GraviticScanAbility.java", "GraviticScanAbility_8java.html", "GraviticScanAbility_8java" ],
    [ "GraviticScanData.java", "GraviticScanData_8java.html", "GraviticScanData_8java" ],
    [ "InterdictionPulseAbility.java", "InterdictionPulseAbility_8java.html", "InterdictionPulseAbility_8java" ],
    [ "RemoteSurveyAbility.java", "RemoteSurveyAbility_8java.html", "RemoteSurveyAbility_8java" ],
    [ "ReversePolarityToggle.java", "ReversePolarityToggle_8java.html", "ReversePolarityToggle_8java" ],
    [ "ScavengeAbility.java", "ScavengeAbility_8java.html", "ScavengeAbility_8java" ],
    [ "SensorBurstAbility.java", "SensorBurstAbility_8java.html", "SensorBurstAbility_8java" ],
    [ "SustainedBurnAbility.java", "SustainedBurnAbility_8java.html", "SustainedBurnAbility_8java" ],
    [ "ToggleAbilityWithCost.java", "ToggleAbilityWithCost_8java.html", "ToggleAbilityWithCost_8java" ],
    [ "TransponderAbility.java", "TransponderAbility_8java.html", "TransponderAbility_8java" ]
];