var DistressCallResponsePirateAssignmentAI_8java =
[
    [ "com.fs.starfarer.api.impl.campaign.abilities.DistressCallResponsePirateAssignmentAI", "classcom_1_1fs_1_1starfarer_1_1api_1_1impl_1_1campaign_1_1abilities_1_1DistressCallResponsePirateAssignmentAI.html", "classcom_1_1fs_1_1starfarer_1_1api_1_1impl_1_1campaign_1_1abilities_1_1DistressCallResponsePirateAssignmentAI" ]
];