var EveryFrameWeaponEffectPluginWithAdvanceAfter_8java =
[
    [ "com.fs.starfarer.api.combat.EveryFrameWeaponEffectPluginWithAdvanceAfter", "interfacecom_1_1fs_1_1starfarer_1_1api_1_1combat_1_1EveryFrameWeaponEffectPluginWithAdvanceAfter.html", "interfacecom_1_1fs_1_1starfarer_1_1api_1_1combat_1_1EveryFrameWeaponEffectPluginWithAdvanceAfter" ]
];