var HAKazeronTacBombardmentFactor_8java =
[
    [ "com.fs.starfarer.api.impl.campaign.intel.events.HAKazeronTacBombardmentFactor", "classcom_1_1fs_1_1starfarer_1_1api_1_1impl_1_1campaign_1_1intel_1_1events_1_1HAKazeronTacBombardmentFactor.html", "classcom_1_1fs_1_1starfarer_1_1api_1_1impl_1_1campaign_1_1intel_1_1events_1_1HAKazeronTacBombardmentFactor" ]
];