var IndustryOptionProvider_8java =
[
    [ "com.fs.starfarer.api.campaign.listeners.IndustryOptionProvider", "interfacecom_1_1fs_1_1starfarer_1_1api_1_1campaign_1_1listeners_1_1IndustryOptionProvider.html", "interfacecom_1_1fs_1_1starfarer_1_1api_1_1campaign_1_1listeners_1_1IndustryOptionProvider" ],
    [ "com.fs.starfarer.api.campaign.listeners.IndustryOptionProvider.IndustryOptionData", "classcom_1_1fs_1_1starfarer_1_1api_1_1campaign_1_1listeners_1_1IndustryOptionProvider_1_1IndustryOptionData.html", "classcom_1_1fs_1_1starfarer_1_1api_1_1campaign_1_1listeners_1_1IndustryOptionProvider_1_1IndustryOptionData" ]
];