var interfacecom_1_1fs_1_1starfarer_1_1api_1_1campaign_1_1listeners_1_1SubmarketInteractionListener =
[
    [ "SubmarketInteractionType", "enumcom_1_1fs_1_1starfarer_1_1api_1_1campaign_1_1listeners_1_1SubmarketInteractionListener_1_1SubmarketInteractionType.html", null ]
];