var SpecialItemRaidObjectivePluginImpl_8java =
[
    [ "com.fs.starfarer.api.impl.campaign.graid.SpecialItemRaidObjectivePluginImpl", "classcom_1_1fs_1_1starfarer_1_1api_1_1impl_1_1campaign_1_1graid_1_1SpecialItemRaidObjectivePluginImpl.html", "classcom_1_1fs_1_1starfarer_1_1api_1_1impl_1_1campaign_1_1graid_1_1SpecialItemRaidObjectivePluginImpl" ]
];