var TransmitterTrapSpecial_8java =
[
    [ "com.fs.starfarer.api.impl.campaign.rulecmd.salvage.special.TransmitterTrapSpecial", "classcom_1_1fs_1_1starfarer_1_1api_1_1impl_1_1campaign_1_1rulecmd_1_1salvage_1_1special_1_1TransmitterTrapSpecial.html", "classcom_1_1fs_1_1starfarer_1_1api_1_1impl_1_1campaign_1_1rulecmd_1_1salvage_1_1special_1_1TransmitterTrapSpecial" ]
];