var TutorialPirateApproachesDialogPluginImpl_8java =
[
    [ "com.fs.starfarer.api.impl.campaign.tutorial.TutorialPirateApproachesDialogPluginImpl", "classcom_1_1fs_1_1starfarer_1_1api_1_1impl_1_1campaign_1_1tutorial_1_1TutorialPirateApproachesDialogPluginImpl.html", "classcom_1_1fs_1_1starfarer_1_1api_1_1impl_1_1campaign_1_1tutorial_1_1TutorialPirateApproachesDialogPluginImpl" ]
];