package com.fs.starfarer.api.characters;

public enum SkillEffectType {
	SHIP,
	ALL_SHIPS_IN_FLEET,
	SHIP_FIGHTERS,
	ALL_FIGHTERS_IN_FLEET,
	CHARACTER_STATS,
	FLEET,
	HULLMOD_UNLOCK,
	ABILITY_UNLOCK,
	GOVERNED_OUTPOST,
	ALL_OUTPOSTS,
	DESCRIPTION,
}
