var DisposableHostileActivityFleetManager_8java =
[
    [ "com.fs.starfarer.api.impl.campaign.intel.events.DisposableHostileActivityFleetManager", "d6/d93/classcom_1_1fs_1_1starfarer_1_1api_1_1impl_1_1campaign_1_1intel_1_1events_1_1DisposableHostileActivityFleetManager.html", "d6/d93/classcom_1_1fs_1_1starfarer_1_1api_1_1impl_1_1campaign_1_1intel_1_1events_1_1DisposableHostileActivityFleetManager" ]
];