var LuddicPathAgreementHostileActivityCause2_8java =
[
    [ "com.fs.starfarer.api.impl.campaign.intel.events.LuddicPathAgreementHostileActivityCause2", "d8/d8e/classcom_1_1fs_1_1starfarer_1_1api_1_1impl_1_1campaign_1_1intel_1_1events_1_1LuddicPathAgreementHostileActivityCause2.html", "d8/d8e/classcom_1_1fs_1_1starfarer_1_1api_1_1impl_1_1campaign_1_1intel_1_1events_1_1LuddicPathAgreementHostileActivityCause2" ]
];