package com.fs.starfarer.api.combat;

public enum CombatEngineLayers {
	BELOW_PLANETS,
	PLANET_LAYER,
	ABOVE_PLANETS,
	CLOUD_LAYER,
	BELOW_SHIPS_LAYER,
	UNDER_SHIPS_LAYER,
	ASTEROIDS_LAYER,
	CAPITAL_SHIPS_LAYER,
	CRUISERS_LAYER,
	DESTROYERS_LAYER,
	FRIGATES_LAYER,
	BELOW_PHASED_SHIPS_LAYER,
	PHASED_SHIPS_LAYER, //need to be below fighters to avoid artifacts when phasing back in
	STATION_WEAPONS_LAYER,
	CONTRAILS_LAYER,
	FIGHTERS_LAYER,
	BELOW_INDICATORS_LAYER,
	FF_INDICATORS_LAYER,
	ABOVE_SHIPS_LAYER,
	ABOVE_SHIPS_AND_MISSILES_LAYER,
	ABOVE_PARTICLES_LOWER,
	ABOVE_PARTICLES,
	JUST_BELOW_WIDGETS,
}
