package com.fs.starfarer.api.campaign;

public enum TerrainAIFlags {
	BREAK_OTHER_ORBITS,
	
	CR_DRAIN,
	
	TILE_BASED,
	EFFECT_DIMINISHED_WITH_RANGE,
	
	REDUCES_DETECTABILITY,
	REDUCES_SENSOR_RANGE,
	HIDING_STATIONARY,
	
	REDUCES_SPEED_SMALL,
	REDUCES_SPEED_LARGE,
	REDUCES_SPEED_ALL,
	
	DANGEROUS_UNLESS_GO_SLOW,
	NOT_SUPER_DANGEROUS_UNLESS_GO_SLOW,
	
	MOVES_FLEETS,
	
	AVOID_VERY_CAREFULLY,
}
